graph:
    shape: clique

org:
    crowd:
        bcw:
            prototype: true
            dev: true

spring:
    mail:
        host: smtp.gmail.com

#How /when is this used?
security:
  user:
    password: password